config/routes.rb
Rails.application.routes.draw do
  resources :meals
  resources :schools
  resources :kinds
  resources :ages
  resources :executions
  resources :groups

  get 'welcome', to: 'pages#welcome'
  get 'landing', to: 'pages#landing'

  root 'pages#landing'
end

app/models/execution.rb
class Execution < ApplicationRecord
end

app/controllers/executions_controller.rb
class ExecutionsController < ApplicationController
  before_action :set_execution, only: [:show, :edit, :update, :destroy]

  # GET /executions
  # GET /executions.json
  def index
    @executions = Execution.all
  end

  # GET /executions/1
  # GET /executions/1.json
  def show
  end

  # GET /executions/new
  def new
    @execution = Execution.new
  end

  # GET /executions/1/edit
  def edit
  end

  # POST /executions
  # POST /executions.json
  def create
    @execution = Execution.new(execution_params)

    respond_to do |format|
      if @execution.save
        format.html { redirect_to @execution, notice: 'Execution was successfully created.' }
        format.json { render :show, status: :created, location: @execution }
      else
        format.html { render :new }
        format.json { render json: @execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /executions/1
  # PATCH/PUT /executions/1.json
  def update
    respond_to do |format|
      if @execution.update(execution_params)
        format.html { redirect_to @execution, notice: 'Execution was successfully updated.' }
        format.json { render :show, status: :ok, location: @execution }
      else
        format.html { render :edit }
        format.json { render json: @execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /executions/1
  # DELETE /executions/1.json
  def destroy
    @execution.destroy
    respond_to do |format|
      format.html { redirect_to executions_url, notice: 'Execution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_execution
      @execution = Execution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def execution_params
      params.require(:execution).permit(:name)
    end
end

app/helpers/executions_helper.rb
module ExecutionsHelper
end

app/views/executions/_form.html.erb
<%= simple_form_for(@execution) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/executions/edit.html.erb
<h1>Editing Execution</h1>

<%= render 'form', execution: @execution %>

<%= link_to 'Show', @execution %> |
<%= link_to 'Back', executions_path %>

app/views/executions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Executions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @executions.each do |execution| %>
      <tr>
        <td><%= execution.name %></td>
        <td><%= link_to 'Show', execution %></td>
        <td><%= link_to 'Edit', edit_execution_path(execution) %></td>
        <td><%= link_to 'Destroy', execution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Execution', new_execution_path %>

app/views/executions/new.html.erb
<h1>New Execution</h1>

<%= render 'form', execution: @execution %>

<%= link_to 'Back', executions_path %>

app/views/executions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @execution.name %>
</p>

<%= link_to 'Edit', edit_execution_path(@execution) %> |
<%= link_to 'Back', executions_path %>