config/routes.rb
Rails.application.routes.draw do
  resources :meals
  resources :schools
  resources :kinds
  resources :ages
  resources :executions
  resources :groups

  get 'welcome', to: 'pages#welcome'
  get 'landing', to: 'pages#landing'

  root 'pages#landing'
end

app/models/age.rb
class Age < ApplicationRecord
end

app/controllers/ages_controller.rb
class AgesController < ApplicationController
  before_action :set_age, only: [:show, :edit, :update, :destroy]

  # GET /ages
  # GET /ages.json
  def index
    @ages = Age.all
  end

  # GET /ages/1
  # GET /ages/1.json
  def show
  end

  # GET /ages/new
  def new
    @age = Age.new
  end

  # GET /ages/1/edit
  def edit
  end

  # POST /ages
  # POST /ages.json
  def create
    @age = Age.new(age_params)

    respond_to do |format|
      if @age.save
        format.html { redirect_to @age, notice: 'Age was successfully created.' }
        format.json { render :show, status: :created, location: @age }
      else
        format.html { render :new }
        format.json { render json: @age.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ages/1
  # PATCH/PUT /ages/1.json
  def update
    respond_to do |format|
      if @age.update(age_params)
        format.html { redirect_to @age, notice: 'Age was successfully updated.' }
        format.json { render :show, status: :ok, location: @age }
      else
        format.html { render :edit }
        format.json { render json: @age.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ages/1
  # DELETE /ages/1.json
  def destroy
    @age.destroy
    respond_to do |format|
      format.html { redirect_to ages_url, notice: 'Age was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_age
      @age = Age.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def age_params
      params.require(:age).permit(:name)
    end
end

app/helpers/ages_helper.rb
module AgesHelper
end

app/views/ages/_form.html.erb
<%= simple_form_for(@age) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ages/edit.html.erb
<h1>Editing Age</h1>

<%= render 'form', age: @age %>

<%= link_to 'Show', @age %> |
<%= link_to 'Back', ages_path %>

app/views/ages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ages.each do |age| %>
      <tr>
        <td><%= age.name %></td>
        <td><%= link_to 'Show', age %></td>
        <td><%= link_to 'Edit', edit_age_path(age) %></td>
        <td><%= link_to 'Destroy', age, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Age', new_age_path %>

app/views/ages/new.html.erb
<h1>New Age</h1>

<%= render 'form', age: @age %>

<%= link_to 'Back', ages_path %>

app/views/ages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @age.name %>
</p>

<%= link_to 'Edit', edit_age_path(@age) %> |
<%= link_to 'Back', ages_path %>